In [1]:
import lsdb

In [2]:
cat = lsdb.open_catalog("../tests/data/small_sky_order1_collection")
cat

Dask NestedFrame Structure:
                                 id               ra              dec        ra_error       dec_error
npartitions=4
3170534137668829184  int64[pyarrow]  double[pyarrow]  double[pyarrow]  int64[pyarrow]  int64[pyarrow]
3242591731706757120             ...              ...              ...             ...             ...
3314649325744685056             ...              ...              ...             ...             ...
3386706919782612992             ...              ...              ...             ...             ...
3458764513820540928             ...              ...              ...             ...             ...
Dask Name: nestedframe, 3 expressions
Expr=MapPartitions(NestedFrame)

In [3]:
sources = lsdb.open_catalog("../tests/data/small_sky_source",
                            margin_cache="../tests/data/small_sky_source_margin")
sources

Dask NestedFrame Structure:
                          source_id        source_ra       source_dec              mjd              mag             band       object_id        object_ra       object_dec
npartitions=14
1188950301625810944  int64[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  string[pyarrow]  int64[pyarrow]  double[pyarrow]  double[pyarrow]
3170534137668829184             ...              ...              ...              ...              ...              ...             ...              ...              ...
...                             ...              ...              ...              ...              ...              ...             ...              ...              ...
3386706919782612992             ...              ...              ...              ...              ...              ...             ...              ...              ...
3458764513820540928             ...              ...              ...              ...              ...              ...             ...              ...              ...
Dask Name: nestedframe, 3 expressions
Expr=MapPartitions(NestedFrame)

In [4]:
cat.crossmatch(sources).partitions[0].compute()

/Users/smcmu/code/lsdb/src/lsdb/catalog/catalog.py:358: FutureWarning: The default suffix behavior will change from applying suffixes to all columns to only applying suffixes to overlapping columns in a future release.To maintain the current behavior, explicitly set `suffix_method='all_columns'`. To change to the new behavior, set `suffix_method='overlapping_columns'`.
  warnings.warn(

Computing Catalog:   0%|          | 0/11 [00:00<?, ?it/s]

Empty NestedFrame
Columns: [id_small_sky_order1, ra_small_sky_order1, dec_small_sky_order1, ra_error_small_sky_order1, dec_error_small_sky_order1, source_id_small_sky_source, source_ra_small_sky_source, source_dec_small_sky_source, mjd_small_sky_source, mag_small_sky_source, band_small_sky_source, object_id_small_sky_source, object_ra_small_sky_source, object_dec_small_sky_source, _dist_arcsec]
Index: []