In [1]:
from lsdb_custom_graphs import lsdb

In [2]:
from distributed import Client

# with Client() as c:
lsdb.open_catalog("../tests/data/small_sky_order1_collection").compute()

                      id     ra   dec  ra_error  dec_error
_healpix_29
3187422220182231470  707  308.5 -69.5         0          0
3187796123455121090  792  320.5 -69.5         0          0
...                  ...    ...   ...       ...        ...
3400255793565258227  767  314.5 -29.5         0          0
3424180623569024089  743  307.5 -25.5         0          0

[131 rows x 5 columns]

In [6]:
lsdb.open_catalog("../tests/data/small_sky_order1_collection")

                      id     ra   dec  ra_error  dec_error
_healpix_29
3302771647141634889  779  347.5 -29.5         0          0
3245124716102589287  812  346.5 -60.5         0          0
3278748473083867004  821  330.5 -52.5         0          0
3279291389443808596  762  327.5 -51.5         0          0
3315911807729485378  788  283.5 -61.5         0          0
3319374857273532192  793  289.5 -58.5         0          0
3333910191588745371  711  305.5 -49.5         0          0
3333964020129680240  802  304.5 -49.5         0          0
3196723640945762243  772  348.5 -64.5         0          0
3205876081882660000  739  332.5 -57.5         0          0
3231100210201107330  758  325.5 -53.5         0          0
3231184305677168587  780  326.5 -52.5         0          0
3239635329517312051  787  320.5 -47.5         0          0
3388235695417907461  756  319.5 -35.5         0          0
3391463069396352355  796  320.5 -33.5         0          0
3224426300283981710  818  300.5 -55.5         0          0
3236559609654922833  822  301.5 -54.5         0          0
3236880878436655047  736  303.5 -52.5         0          0
3237753854591418539  830  306.5 -50.5         0          0
3308757303244427140  761  329.5 -29.5         0          0
3309847189890492293  828  330.5 -26.5         0          0
3348147488166171508  765  306.5 -35.5         0          0
3348397106556162456  740  306.5 -33.5         0          0

In [7]:
a =:10
a

SyntaxError: invalid syntax (380339231.py, line 1)

In [ ]:
a