In [1]:
from lsdb_custom_graphs import lsdb

In [2]:
from distributed import Client

# with Client() as c:
lsdb.open_catalog("../tests/data/small_sky_order1_collection").compute()

                      id     ra   dec  ra_error  dec_error
_healpix_29
3187422220182231470  707  308.5 -69.5         0          0
3187796123455121090  792  320.5 -69.5         0          0
...                  ...    ...   ...       ...        ...
3400255793565258227  767  314.5 -29.5         0          0
3424180623569024089  743  307.5 -25.5         0          0

[131 rows x 5 columns]

In [3]:
cat = lsdb.open_catalog("../tests/data/small_sky_order1_collection")
cat

LSDB expr Catalog(operation=FromHealpixMap(read_pixel)) Schema:
Empty NestedFrame
Columns: [id, ra, dec, ra_error, dec_error]
Index: []

In [4]:
cat.operation

FromHealpixMap(read_pixel)

In [11]:
cat[["id"]].operation.optimize().build().graph[('read_pixel-8b7f3f9856fbfdce0fc1eb70c9e55ce9',
                                                0)].kwargs

{'path_generator': <function hats.io.paths.pixel_catalog_file(catalog_base_dir: 'str | Path | UPath | None', pixel: 'HealpixPixel', query_params: 'dict | None' = None, npix_suffix: 'str' = '.parquet') -> 'UPath'>,
 'catalog_base_dir': PosixUPath('../tests/data/small_sky_order1_collection/small_sky_order1'),
 'npix_suffix': '.parquet',
 'query_url_params': None,
 'schema': _healpix_29: int64
 id: int64
 ra: double
 dec: double
 ra_error: int64
 dec_error: int64,
 'filters': None,
 'index_column': '_healpix_29',
 'is_dir': False,
 'columns': ['id']}

In [10]:
cat[["id"]].operation.handle_projections([]).base.kwargs

{'path_generator': <function hats.io.paths.pixel_catalog_file(catalog_base_dir: 'str | Path | UPath | None', pixel: 'HealpixPixel', query_params: 'dict | None' = None, npix_suffix: 'str' = '.parquet') -> 'UPath'>,
 'catalog_base_dir': PosixUPath('../tests/data/small_sky_order1_collection/small_sky_order1'),
 'npix_suffix': '.parquet',
 'query_url_params': None,
 'schema': _healpix_29: int64
 id: int64
 ra: double
 dec: double
 ra_error: int64
 dec_error: int64,
 'filters': None,
 'index_column': '_healpix_29',
 'is_dir': False,
 'columns': ['id']}

In [7]:
sources = lsdb.open_catalog("../tests/data/small_sky_source")
sources

LSDB expr Catalog(operation=FromHealpixMap(read_pixel)) Schema:
Empty NestedFrame
Columns: [source_id, source_ra, source_dec, mjd, mag, band, object_id, object_ra, object_dec]
Index: []

In [8]:
cat.crossmatch(sources).operation.build().graph

/Users/smcmu/code/custom-graphs/src/lsdb_custom_graphs/lsdb/catalog.py:218: FutureWarning: The default suffix behavior will change from applying suffixes to all columns to only applying suffixes to overlapping columns in a future release.To maintain the current behavior, explicitly set `suffix_method='all_columns'`. To change to the new behavior, set `suffix_method='overlapping_columns'`.
  warnings.warn(
/Users/smcmu/code/custom-graphs/src/lsdb_custom_graphs/lsdb/crossmatch_catalog_data.py:478: RuntimeWarning: Right catalog does not have a margin cache. Results may be incomplete and/or inaccurate.
  warnings.warn(

{('perform_crossmatch-5cd967fd0a8489cee22a6025e394d9ed',
  2): <Task ('perform_crossmatch-5cd967fd0a8489cee22a6025e394d9ed', 2) perform_crossmatch(...)>,
 ('perform_crossmatch-5cd967fd0a8489cee22a6025e394d9ed',
  8): <Task ('perform_crossmatch-5cd967fd0a8489cee22a6025e394d9ed', 8) perform_crossmatch(...)>,
 ('perform_crossmatch-5cd967fd0a8489cee22a6025e394d9ed',
  11): <Task ('perform_crossmatch-5cd967fd0a8489cee22a6025e394d9ed', 11) perform_crossmatch(...)>,
 ('perform_crossmatch-5cd967fd0a8489cee22a6025e394d9ed',
  1): <Task ('perform_crossmatch-5cd967fd0a8489cee22a6025e394d9ed', 1) perform_crossmatch(...)>,
 ('perform_crossmatch-5cd967fd0a8489cee22a6025e394d9ed',
  7): <Task ('perform_crossmatch-5cd967fd0a8489cee22a6025e394d9ed', 7) perform_crossmatch(...)>,
 ('perform_crossmatch-5cd967fd0a8489cee22a6025e394d9ed',
  4): <Task ('perform_crossmatch-5cd967fd0a8489cee22a6025e394d9ed', 4) perform_crossmatch(...)>,
 ('perform_crossmatch-5cd967fd0a8489cee22a6025e394d9ed',
  10): <Task ('perform_crossmatch-5cd967fd0a8489cee22a6025e394d9ed', 10) perform_crossmatch(...)>,
 ('read_pixel-eedeae3fb73d898006f42d5f52044dcc',
  1): <Task ('read_pixel-eedeae3fb73d898006f42d5f52044dcc', 1) read_pixel(..., ...)>,
 ('read_pixel-6c140b017ccfd5b4f355b6b85a0a27c1',
  2): <Task ('read_pixel-6c140b017ccfd5b4f355b6b85a0a27c1', 2) read_pixel(..., ...)>,
 ('read_pixel-6c140b017ccfd5b4f355b6b85a0a27c1',
  5): <Task ('read_pixel-6c140b017ccfd5b4f355b6b85a0a27c1', 5) read_pixel(..., ...)>,
 ('read_pixel-6c140b017ccfd5b4f355b6b85a0a27c1',
  11): <Task ('read_pixel-6c140b017ccfd5b4f355b6b85a0a27c1', 11) read_pixel(..., ...)>,
 ('read_pixel-6c140b017ccfd5b4f355b6b85a0a27c1',
  8): <Task ('read_pixel-6c140b017ccfd5b4f355b6b85a0a27c1', 8) read_pixel(..., ...)>,
 ('perform_crossmatch-5cd967fd0a8489cee22a6025e394d9ed',
  5): <Task ('perform_crossmatch-5cd967fd0a8489cee22a6025e394d9ed', 5) perform_crossmatch(...)>,
 ('read_pixel-eedeae3fb73d898006f42d5f52044dcc',
  2): <Task ('read_pixel-eedeae3fb73d898006f42d5f52044dcc', 2) read_pixel(..., ...)>,
 ('read_pixel-6c140b017ccfd5b4f355b6b85a0a27c1',
  6): <Task ('read_pixel-6c140b017ccfd5b4f355b6b85a0a27c1', 6) read_pixel(..., ...)>,
 ('read_pixel-6c140b017ccfd5b4f355b6b85a0a27c1',
  3): <Task ('read_pixel-6c140b017ccfd5b4f355b6b85a0a27c1', 3) read_pixel(..., ...)>,
 ('read_pixel-6c140b017ccfd5b4f355b6b85a0a27c1',
  9): <Task ('read_pixel-6c140b017ccfd5b4f355b6b85a0a27c1', 9) read_pixel(..., ...)>,
 ('perform_crossmatch-5cd967fd0a8489cee22a6025e394d9ed',
  0): <Task ('perform_crossmatch-5cd967fd0a8489cee22a6025e394d9ed', 0) perform_crossmatch(...)>,
 ('read_pixel-6c140b017ccfd5b4f355b6b85a0a27c1',
  12): <Task ('read_pixel-6c140b017ccfd5b4f355b6b85a0a27c1', 12) read_pixel(..., ...)>,
 ('perform_crossmatch-5cd967fd0a8489cee22a6025e394d9ed',
  3): <Task ('perform_crossmatch-5cd967fd0a8489cee22a6025e394d9ed', 3) perform_crossmatch(...)>,
 ('read_pixel-eedeae3fb73d898006f42d5f52044dcc',
  0): <Task ('read_pixel-eedeae3fb73d898006f42d5f52044dcc', 0) read_pixel(..., ...)>,
 ('perform_crossmatch-5cd967fd0a8489cee22a6025e394d9ed',
  6): <Task ('perform_crossmatch-5cd967fd0a8489cee22a6025e394d9ed', 6) perform_crossmatch(...)>,
 ('perform_crossmatch-5cd967fd0a8489cee22a6025e394d9ed',
  12): <Task ('perform_crossmatch-5cd967fd0a8489cee22a6025e394d9ed', 12) perform_crossmatch(...)>,
 ('perform_crossmatch-5cd967fd0a8489cee22a6025e394d9ed',
  9): <Task ('perform_crossmatch-5cd967fd0a8489cee22a6025e394d9ed', 9) perform_crossmatch(...)>,
 ('read_pixel-6c140b017ccfd5b4f355b6b85a0a27c1',
  4): <Task ('read_pixel-6c140b017ccfd5b4f355b6b85a0a27c1', 4) read_pixel(..., ...)>,
 ('read_pixel-6c140b017ccfd5b4f355b6b85a0a27c1',
  1): <Task ('read_pixel-6c140b017ccfd5b4f355b6b85a0a27c1', 1) read_pixel(..., ...)>,
 ('read_pixel-6c140b017ccfd5b4f355b6b85a0a27c1',
  7): <Task ('read_pixel-6c140b017ccfd5b4f355b6b85a0a27c1', 7) read_pixel(..., ...)>,
 ('read_pixel-6c140b017ccfd5b4f355b6b85a0a27c1',
  13): <Task ('read_pixel-6c140b017ccfd5b4f355b6b85a0a27c1', 13) read_pixel(..., ...)>,
 ('read_pixel-6c140b017ccfd5b4f355b6b85a0a27c1',
  10): <Task ('read_pixel-6c140b017ccfd5b4f355b6b85a0a27c1', 10) read_pixel(..., ...)>,
 ('read_pixel-eedeae3fb73d898006f42d5f52044dcc',
  3): <Task ('read_pixel-eedeae3fb73d898006f42d5f52044dcc', 3) read_pixel(..., ...)>}