In [1]:
from lsdb_custom_graphs import lsdb

In [2]:
from distributed import Client

# with Client() as c:
lsdb.open_catalog("../tests/data/small_sky_order1_collection").compute()

                      id     ra   dec  ra_error  dec_error
_healpix_29
3187422220182231470  707  308.5 -69.5         0          0
3187796123455121090  792  320.5 -69.5         0          0
...                  ...    ...   ...       ...        ...
3400255793565258227  767  314.5 -29.5         0          0
3424180623569024089  743  307.5 -25.5         0          0

[131 rows x 5 columns]

In [2]:
cat = lsdb.open_catalog("../tests/data/small_sky_order1_collection")
cat

LSDB expr Catalog(operation=FromHealpixMap(read_pixel)) Schema:
Empty NestedFrame
Columns: [id, ra, dec, ra_error, dec_error]
Index: []

In [3]:
cat.operation

FromHealpixMap(read_pixel)

In [4]:
sources = lsdb.open_catalog("../tests/data/small_sky_source")
sources

LSDB expr Catalog(operation=FromHealpixMap(read_pixel)) Schema:
Empty NestedFrame
Columns: [source_id, source_ra, source_dec, mjd, mag, band, object_id, object_ra, object_dec]
Index: []

In [7]:
cat.crossmatch(sources).operation.build().graph

/Users/smcmu/code/custom-graphs/src/lsdb_custom_graphs/lsdb/catalog.py:218: FutureWarning: The default suffix behavior will change from applying suffixes to all columns to only applying suffixes to overlapping columns in a future release.To maintain the current behavior, explicitly set `suffix_method='all_columns'`. To change to the new behavior, set `suffix_method='overlapping_columns'`.
  warnings.warn(
/Users/smcmu/code/custom-graphs/src/lsdb_custom_graphs/lsdb/crossmatch_catalog_data.py:478: RuntimeWarning: Right catalog does not have a margin cache. Results may be incomplete and/or inaccurate.
  warnings.warn(

{('perform_crossmatch-8d79517b261ffe304f5c4ec1ab9d7167',
  0): <Task ('perform_crossmatch-8d79517b261ffe304f5c4ec1ab9d7167', 0) perform_crossmatch(...)>,
 ('perform_crossmatch-8d79517b261ffe304f5c4ec1ab9d7167',
  6): <Task ('perform_crossmatch-8d79517b261ffe304f5c4ec1ab9d7167', 6) perform_crossmatch(...)>,
 ('perform_crossmatch-8d79517b261ffe304f5c4ec1ab9d7167',
  9): <Task ('perform_crossmatch-8d79517b261ffe304f5c4ec1ab9d7167', 9) perform_crossmatch(...)>,
 ('read_pixel-e3139a8d64b77c2891ecfc129c0a1073',
  1): <Task ('read_pixel-e3139a8d64b77c2891ecfc129c0a1073', 1) read_pixel(..., ...)>,
 ('perform_crossmatch-8d79517b261ffe304f5c4ec1ab9d7167',
  12): <Task ('perform_crossmatch-8d79517b261ffe304f5c4ec1ab9d7167', 12) perform_crossmatch(...)>,
 ('perform_crossmatch-8d79517b261ffe304f5c4ec1ab9d7167',
  1): <Task ('perform_crossmatch-8d79517b261ffe304f5c4ec1ab9d7167', 1) perform_crossmatch(...)>,
 ('perform_crossmatch-8d79517b261ffe304f5c4ec1ab9d7167',
  4): <Task ('perform_crossmatch-8d79517b261ffe304f5c4ec1ab9d7167', 4) perform_crossmatch(...)>,
 ('perform_crossmatch-8d79517b261ffe304f5c4ec1ab9d7167',
  10): <Task ('perform_crossmatch-8d79517b261ffe304f5c4ec1ab9d7167', 10) perform_crossmatch(...)>,
 ('perform_crossmatch-8d79517b261ffe304f5c4ec1ab9d7167',
  7): <Task ('perform_crossmatch-8d79517b261ffe304f5c4ec1ab9d7167', 7) perform_crossmatch(...)>,
 ('read_pixel-e3139a8d64b77c2891ecfc129c0a1073',
  2): <Task ('read_pixel-e3139a8d64b77c2891ecfc129c0a1073', 2) read_pixel(..., ...)>,
 ('perform_crossmatch-8d79517b261ffe304f5c4ec1ab9d7167',
  2): <Task ('perform_crossmatch-8d79517b261ffe304f5c4ec1ab9d7167', 2) perform_crossmatch(...)>,
 ('perform_crossmatch-8d79517b261ffe304f5c4ec1ab9d7167',
  8): <Task ('perform_crossmatch-8d79517b261ffe304f5c4ec1ab9d7167', 8) perform_crossmatch(...)>,
 ('perform_crossmatch-8d79517b261ffe304f5c4ec1ab9d7167',
  5): <Task ('perform_crossmatch-8d79517b261ffe304f5c4ec1ab9d7167', 5) perform_crossmatch(...)>,
 ('perform_crossmatch-8d79517b261ffe304f5c4ec1ab9d7167',
  11): <Task ('perform_crossmatch-8d79517b261ffe304f5c4ec1ab9d7167', 11) perform_crossmatch(...)>,
 ('read_pixel-e3139a8d64b77c2891ecfc129c0a1073',
  0): <Task ('read_pixel-e3139a8d64b77c2891ecfc129c0a1073', 0) read_pixel(..., ...)>,
 ('read_pixel-e3139a8d64b77c2891ecfc129c0a1073',
  3): <Task ('read_pixel-e3139a8d64b77c2891ecfc129c0a1073', 3) read_pixel(..., ...)>,
 ('read_pixel-76fdd82ed173868ebea07952b76d2fd5',
  1): <Task ('read_pixel-76fdd82ed173868ebea07952b76d2fd5', 1) read_pixel(..., ...)>,
 ('perform_crossmatch-8d79517b261ffe304f5c4ec1ab9d7167',
  3): <Task ('perform_crossmatch-8d79517b261ffe304f5c4ec1ab9d7167', 3) perform_crossmatch(...)>,
 ('read_pixel-76fdd82ed173868ebea07952b76d2fd5',
  7): <Task ('read_pixel-76fdd82ed173868ebea07952b76d2fd5', 7) read_pixel(..., ...)>,
 ('read_pixel-76fdd82ed173868ebea07952b76d2fd5',
  13): <Task ('read_pixel-76fdd82ed173868ebea07952b76d2fd5', 13) read_pixel(..., ...)>,
 ('read_pixel-76fdd82ed173868ebea07952b76d2fd5',
  10): <Task ('read_pixel-76fdd82ed173868ebea07952b76d2fd5', 10) read_pixel(..., ...)>,
 ('read_pixel-76fdd82ed173868ebea07952b76d2fd5',
  2): <Task ('read_pixel-76fdd82ed173868ebea07952b76d2fd5', 2) read_pixel(..., ...)>,
 ('read_pixel-76fdd82ed173868ebea07952b76d2fd5',
  8): <Task ('read_pixel-76fdd82ed173868ebea07952b76d2fd5', 8) read_pixel(..., ...)>,
 ('read_pixel-76fdd82ed173868ebea07952b76d2fd5',
  5): <Task ('read_pixel-76fdd82ed173868ebea07952b76d2fd5', 5) read_pixel(..., ...)>,
 ('read_pixel-76fdd82ed173868ebea07952b76d2fd5',
  11): <Task ('read_pixel-76fdd82ed173868ebea07952b76d2fd5', 11) read_pixel(..., ...)>,
 ('read_pixel-76fdd82ed173868ebea07952b76d2fd5',
  6): <Task ('read_pixel-76fdd82ed173868ebea07952b76d2fd5', 6) read_pixel(..., ...)>,
 ('read_pixel-76fdd82ed173868ebea07952b76d2fd5',
  3): <Task ('read_pixel-76fdd82ed173868ebea07952b76d2fd5', 3) read_pixel(..., ...)>,
 ('read_pixel-76fdd82ed173868ebea07952b76d2fd5',
  9): <Task ('read_pixel-76fdd82ed173868ebea07952b76d2fd5', 9) read_pixel(..., ...)>,
 ('read_pixel-76fdd82ed173868ebea07952b76d2fd5',
  12): <Task ('read_pixel-76fdd82ed173868ebea07952b76d2fd5', 12) read_pixel(..., ...)>,
 ('read_pixel-76fdd82ed173868ebea07952b76d2fd5',
  4): <Task ('read_pixel-76fdd82ed173868ebea07952b76d2fd5', 4) read_pixel(..., ...)>}